web:
  build: .
#  command: 'bash -c ''npm start'''
#  command: xvfb-run -e meow --server-args="-screen 0 1024x768x24" npm start
  command: ./run.sh
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
